### ISSUE TITLE
Publish 1.1

### ISSUE THREAD

**Issue by zepumph** [phetsims/plinko-probability#100]
From https://github.com/phetsims/tasks/issues/854, we are ready to republish this new version to the phet website.

@ariel-phet please comment on who should do this.

**Comment by ariel-phet** [comment]
@zepumph you should probably get a feel for how this process works. Perhaps could you and @jessegreenberg work together at some point to republish since you two work together pretty frequently at the moment?

**Comment by ariel-phet** [comment]
Marking as medium priority. Would be good to do before the ISTE conference (so by June 23)

**Comment by zepumph** [comment]
Published! Thanks @jessegreenberg for the help. https://phet.colorado.edu/sims/html/plinko-probability/latest/plinko-probability_en.html
