### ISSUE TITLE
QA credits were not updated for 1.1 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#101]
1.1.0 was published (see https://github.com/phetsims/plinko-probability/issues/100) without updating the QA credits.  There are testers in the test matrix that are not identified in the credits.  Get the updates from @phet-steele, commit them to 1.1 and master branches, then publish maintenance release 1.1.1.

**Comment by zepumph** [comment]
Shoot dang, I had no idea that I needed to do this. Where is this documented? I'm not seeing it in sim_deployment.md, but also I could have missed it.

**Comment by pixelzoom** [comment]
Also commit them to the 1.1-phetio branch.

No idea if it's documented anywhere.  I always create an "update QA credits" issue when I start the QA process.

**Comment by zepumph** [comment]
I added the credits to branches: master, 1.1, and 1.1-phetio. They will be updated on next Maintenance release. This will be picked up in https://github.com/phetsims/QA/issues/2. Closing
