### ISSUE TITLE
new screenshot

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#102]
This work was done in https://github.com/phetsims/tasks/issues/876.  Creating this issue here so that it's possible to answer the "what changed about this sim?" question.

@amanda-phet said:
> We need a new screenshot for Plinko now that the minimum number of rows is 1. All settings should be identical.

@phet-steele created the screenshots in master and 1.1 branches.

I'll verify and publish a 1.1 maintenance release.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/tasks/issues/876#issuecomment-314189134, @phet-steele said:
> ... The screenshot is both on master and 1.1, but I'm sure a quick maintenance release off 1.1 would be fine (with no testing).

plinko-probabiltiy has 1.1 and 1.1-phetio branches, indicating that phet and phet-io brands were published together and must be kept in sync.  

Three problems:

(1) I see no commit for the new screenshot in the 1.1-phetio branch.  

(2) package.json for 1.1 has a version id of "1.1.1", 1.1-phetio has "1.1.1-rc.1".  So there's something funny going on here.  Is there an RC test in progress for plinko?

(3) I likely need to publish 1.1 _and_ 1.1-phetio maintenance releases. Can that be confirmed?

**Comment by pixelzoom** [comment]
@jonathanolson I see these commits from you for package.json:

1.1:  https://github.com/phetsims/plinko-probability/commit/19dd37efda2cb7ec7ddcf009ade4c2a037a05de2
1.1-phetio: https://github.com/phetsims/plinko-probability/commit/7ab097ce606235ba6c48c1c3c4d19ed819f0c1db

Why are the version ids different?

**Comment by pixelzoom** [comment]
Let me guess... I'll bet that 1.1.1-phetio never got published, so "version" never got set to "1.1.1" in the 1.1-phetio branch.

**Comment by phet-steele** [comment]
@pixelzoom I have no idea if/how phet-io brand sims use a screenshot. They don't have a "sim page" like phet sims do, so I didn't think it was important to update the phet-io branch. If it's simply for the sake of keeping 1.1-phetio and 1.1 the same, a cherry-pick would be fine.

**Comment by jonathanolson** [comment]
I ran the automated processes for the maintenance release production releases once cleared for https://github.com/phetsims/QA/issues/2, but when I looked at the plinko 1.1-phetio branch I noticed commits on the release branch. I didn't feel comfortable releasing a production version off of SHAs that weren't tested, so I halted and let @zepumph know.

He agreed to finish the handling of the 1.1-phetio branch in https://github.com/phetsims/QA/issues/2#issuecomment-312338696.

The same commits WERE made in the production version of plinko 1.1, but because I don't manually re-check release branches between RC and production, it snuck in untested.

**Comment by jonathanolson** [comment]
FYI, the phetio-specific commit I saw was probably untested was https://github.com/phetsims/plinko-probability/commit/1207fedcc7b41e86f9b2edd4b1ca849147301a40, since it changes phet-io dependencies and was untested in the RC for https://github.com/phetsims/QA/issues/2.

**Comment by pixelzoom** [comment]
@phet-steele 1.1 and 1.1-phetio branches must be kept in sync _regardless of the change_.

@zepumph why are there commits on the 1.1-phetio release branch?

**Comment by phet-steele** [comment]
@pixelzoom cherry-picked with https://github.com/phetsims/plinko-probability/commit/30fae57f9d1284a4adfce90eaebb94fb1d37c133

**Comment by pixelzoom** [comment]
@phet-steele Yes, thanks, I know how to get the screenshot into the 1.1-phetio branch.  

This business with manually maintaining parallel branches for PhET-iO is  a broken process that is making it difficult to do things that should be easy.

**Comment by pixelzoom** [comment]
1.1.2 and 1.1.2-phetio are published.

For 1.1.2, I verified that the new screenshot appears on the sim's webpage, English runs, a couple of translation run.

For 1.1.2-phetio, I verified that the instance-proxies wrapper works.

Closing.
