### ISSUE TITLE
layout of panels is messed up 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#103]
See the "N" in "N = 0":

![screenshot_346](https://user-images.githubusercontent.com/3046552/29146864-ce3339a2-7d20-11e7-9275-adc21ec7a84b.png)

**Comment by jonathanolson** [comment]
If it's using RichText, it's probably similar to https://github.com/phetsims/ph-scale/issues/70.

**Comment by pixelzoom** [comment]
Even more messed up in 2nd screen:

![screenshot_347](https://user-images.githubusercontent.com/3046552/29146894-f03bfa84-7d20-11e7-8eb1-5176e70ab75c.png)

**Comment by pixelzoom** [comment]
Probably related to RichText, similar to https://github.com/phetsims/ph-scale/issues/70.

**Comment by jonathanolson** [comment]
Should be fixed with the above commit, can you verify?

**Comment by pixelzoom** [comment]
👍 Closing.
