### ISSUE TITLE
Keyboard help dialog content and design

### ISSUE THREAD

**Issue by emily-phet** [phetsims/plinko-probability#106]
@arouinfar - can you draft keyboard help content for this sim also?

**Comment by arouinfar** [comment]
@emily-phet @terracoda I think Plinko and Rutherford Scattering (https://github.com/phetsims/rutherford-scattering/issues/136) will have identical dialogs, so I've pasted the content for Rutherford Scattering below.

**Slider Controls**
Adjust slider [left] [right] or [up][down]
Adjust in smaller steps [shift] + [left] [right] or [shift] + [up][down]
Adjust in larger steps [pg up] [pg down]
Jump to minimum [home]
Jump to maximum [end]

**General Navigation**
Move to next item or group [tab]
Move to previous item or group [shift] + [tab]
Move between items in a group [left][right] or [up][down]
Exit a dialog [esc]

![image](https://user-images.githubusercontent.com/8419308/35889387-9a0cfafc-0b58-11e8-9065-cce1faa9fffd.png)

**Comment by terracoda** [comment]
@emily-phet and @arouinfar, the only new interaction in this sim is the accordion box. I'm not sure if users will need guidance on this. It should work like  button, i.e., Space or Enter key open and close it.

**Comment by arouinfar** [comment]
@terracoda I wasn't sure about the accordion boxes either, but decided to leave it out because it behaves like a button, which we haven't been including in the dialogs. I suspect that the open/close will look enough like a button that visual users won't need guidance.

**Comment by terracoda** [comment]
@arouinfar, I think we can move ahead without the accordion box being added. I'll post the text-based HTML version based on the content above.

**Comment by terracoda** [comment]
Here's the text-based HTML for Plinko's Keyboard Shortcuts:
```html
<h1>Keyboard Shortcuts</h1>
<h2>Slider Controls</h2>
<ul>
	<li>Adjust slider Left and Right arrow keys, or Up and Down arrow keys.</li>
	<li>Adjust in smaller steps with Shift plus Left or Right arrow key, or Shift plus Up or Down arrow key.</li>
	<li>Adjust in larger steps with Page Up or Page Down key.</li>
    <li>Jump to minimum with Home key.</li>
    <li>Jump to maximum with End key.</li>
</ul>

<h2>General Navigation</h2>
<ul>
	<li>Move to next item or group with Tab key.</li>
	<li>Move to previous item or group with Shift plus Tab key.</li>
	<li>Move between items in a group with Left and Right Arrow keys or Up and Down Arrow keys.</li>
    <li>Exit a dialog with Escape key.</li>
</ul>
```

**Comment by emily-phet** [comment]
@zepumph or @mbarlow12 Can one of you take this on?

**Comment by zepumph** [comment]
I'm happy to

**Comment by zepumph** [comment]
Implemented in above commit. It is basically the exact same as the Ohms Law panel, but with the group content added. Please see how you like it on phettest. http://phettest.colorado.edu/plinko-probability/plinko-probability_en.html?ea&brand=phet&accessibility

**Comment by arouinfar** [comment]
Dialog looks great @zepumph!

**Comment by pixelzoom** [comment]
Is there anything else to do for this, or can it be closed? Does @terracoda still need to review?

**Comment by emily-phet** [comment]
We'll be circling around to publishing this sim with keyboard nav and other features in 2019. This can be closed for now.
