### ISSUE TITLE
radio button labels are not localized

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#110]
This was discovered while investigating https://github.com/phetsims/plinko-probability/issues/109.

The _Intro_ screen has this control panel:

![screenshot_637](https://user-images.githubusercontent.com/3046552/40377120-558f6cf0-5dad-11e8-9303-6b8fb14673f7.png)

The labels for the radio buttons are not localized.  I expected to find a string for each label in the translations file.  But instead, I find only the word "All", and code that is doing string concatenation to create the labels.  I.e. in `IntroPlayPanel`:

```js
    var oneBall = new HBox( {
      spacing: BALL_RADIUS / 2,
      children: [ new BallNode( BALL_RADIUS ), new Text( timesString + '1', fontOptions ) ]
    } );
    var tenBalls = new HBox( {
      spacing: BALL_RADIUS / 2,
      children: [ new BallNode( BALL_RADIUS ), new Text( timesString + '10', fontOptions ) ]
    } );
    var allBalls = new HBox( {
      spacing: BALL_RADIUS / 2,
      children: [ new BallNode( BALL_RADIUS ), new Text( timesString + allString, fontOptions ) ]
    } );
```

There's seems to be an assumption here that these are mathematical expression and therefore do not need to be localization.   But in this case we're using mathematical expressions as a (possibly locale-specific) shortcut for describing the radio buttons, and that may not translate well.    For example, a translation of "one ball" may work better than "×1" in some languages.

So I think the following strings should be in the translated strings file (where `\u00D7` is Unicode for the times operator):

```js
"oneBall": {
  "value": "\u00D7 1"
},
"tenBalls": {
  "values": "\u00D7 10"
},
"allBalls": {
  "values": "\u00D7 All"
}
```

@amanda-phet Do you agree?

**Comment by pixelzoom** [comment]
@amanda-phet Also wondering why we're using "All" instead of "100".  Why not just use the value so that students know how many balls they are adding?

**Comment by amanda-phet** [comment]
>Also wondering why we're using "All" instead of "100". Why not just use the value so that students know how many balls they are adding?

It's not necessarily 100.. if they dropped 3, then xAll would drop 97 more. We want students to be able to run trials of 100 over and over, and the bins can't really handle more than that, so if someone drops 50 then 100 more, we'd be in trouble.

**Comment by pixelzoom** [comment]
@amanda-phet I don't understand your logic here.  The same argument applies to x10.  Drop 91 balls by doing x10 nine times, then x1.  Then do x10 and it will only release 9 balls.   It's not at all obvious that the upper limit is 100.

**Comment by amanda-phet** [comment]
You're right, I forgot the same thing applies to x10. 

As for the Play button, we are aware that the design choice was problematic and I'm always open to discussing alternatives. Since this sim is being designed for a11y and we are making some minor design changes anyway, we could use this opportunity to make some other changes.

**Comment by amanda-phet** [comment]
Zoom discussion with @pixelzoom . Decided to change the third radio button to x100. This is helpful for translations and is also consistent with how the x10 radio button behaves, so it doesn't seem inconsistent.

**Comment by pixelzoom** [comment]
Change 'x All' to 'x 100' in above commit.  Also use MathSymbols.TIMES.

**Comment by pixelzoom** [comment]
This change will be picked up the next time the sim is published from master.  Leaving issues open and "ready for review" until then.

**Comment by pixelzoom** [comment]
One more thing that I noticed...  There is a `maxBallsIntro` query parameter that can be used to change the max number of balls in the Intro screen.  It's default values is 100.   Rather than hardcoding the string "x 100", this value should be used to create the label.   I made that change in the above commit.    So if you run with `?maxBallsIntro=50`, the radio button will be labeled with "x 50".

**Comment by pixelzoom** [comment]
@amanda-phet please review [1.2.0-dev.4](https://phet-dev.colorado.edu/html/plinko-probability/1.2.0-dev.4/phet/plinko-probability_en_phet.html), then assign back to me.   The only UI change is that "×All" is now "×100" by default.  Or "×50" if you run with `?maxBallsIntro=50`.

**Comment by amanda-phet** [comment]
This looks like it's working well.

**Comment by pixelzoom** [comment]
👍🏻 Closing
