### ISSUE TITLE
Improved sound for balls hitting pegs

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/plinko-probability#13]
We would like to make a much more pleasant sound for the balls in plinko hitting the pegs.

@jbphet is our sound expert. I think something that a gentle bounce would be good, it can be fairly subtle since when many balls are falling if not subtle it will be overwhelming.

**Comment by jbphet** [comment]
I've sent @veillette two sets of sounds with two sounds in each set.  My thinking is that having two different pitches of similar sounds would be somewhat realistic, and less repetitious than having the same sound play over and over.  One set uses a softer, marimba like sound and the other uses more of a click.

I'll assign to @veillette and he can report here whether these sounds will work or if we want to do another iteration.

**Comment by amanda-phet** [comment]
Should we use one sound when the ball falls to the left, and one for when it falls to the right?

**Comment by veillette** [comment]
@Denz1994 has been implementing such a scheme for the sound (left one for a marimba and right for the other marimba sound) . It works very well when there is only one peg falling through the Galton board. The sound gets a bit overwhelming when there are many balls on the board.

**Comment by veillette** [comment]
We showcased the sounds of the marimba at the status meeting. We have limited the number of sounds that gets played. It works well.Closing
