### ISSUE TITLE
plinko-probability list of needed features and bugs to be fixed. 

### ISSUE THREAD

**Issue by veillette** [phetsims/plinko-probability#14]
This issue will track the list of features needed in the sim (05/20/16) to match the design document (DD).

 For the purpose of the list, IT refers to Intro tab and LT refers to the Lab tab and CT is common for both tabs 

- [x] LT - create an Dialog box when the number of balls exceed a constant.
- [x] LT - eraser, count and fraction buttons  should match in size and position the DD 
- [x] CT- create a shadow the for the Galton board to match DD
- [x] CT - create a shadow for the pegs to match DD
- [x] IT - eraser, histogram and cylinder buttons  should match in size and position the DD 
- [x] LT - color of the play-pause button should be green (play) and red (pause) 
- [x] CT - sound should be generated when balls hit the peg (rather than exiting the Galton board) 
- [x] LT - in fraction mode, the numbers in banner should be rounded to 0.001 rather than 0.01
- [x] IT - With the ball size change the ball no longer touches the top of the peg. We will need to change the distance that it travels
- [x] LT - PLay button needs to always be in play position if the option is 'oneBall'
- [x] IT - Path option only adds to one ball unless it is paused and restarted. Continues to add to the bin even after paused.
- [x] LT - 'None' option does not work for only one ball
- [x] IT - Eraser and reset button do not pause the simulation, it erases the balls currently in the sim and sends the remaining balls to the galton board after it has been pressed
- [x] IT - in histogram mode make the ball follow the motion in the lab model rather then the motion designed for the cylinders.
- [x] IT - Cylinder heights and colors need to be adjusted
- [ ] CT - Simulation stops running if active tab in browser is changed. Simulation continues only after it  becomes the active tab in the browser.
- [x] CT - Ball size is too small, compared to DD

**Comment by memo330179** [comment]
- [ ] LT - PLay button needs to always be in play position if the option is 'oneBall'
- [ ] IT - Path option only adds to one bal unless it is paused and restarted. Continues to add to the bin even after paused.
- [ ] LT - 'None' option does not work for only one ball
- [ ] IT - Eraser and reset button do not pause the simulation, it erases the balls currently in the sim and sends the remaining balls to the galton board after it has been pressed

**Comment by Denz1994** [comment]
- [ ] IT - Cylinder heights and colors need to be adjusted
- [ ] CT - Simulation stops running if active tab in browser is changed. Simulation continues only after it  becomes the active tab in the browser.

**Comment by memo330179** [comment]
- [ ] With the ball size change the ball no longer touches the top of the peg. We will need to change the distance that it travels

**Comment by phet-steele** [comment]
> CT - Simulation stops running if active tab in browser is changed. Simulation continues only after it becomes the active tab in the browser.

Saying the sim "stops running" here is not completely accurate. The balls currently on the board freeze in place and the hopper does not release any more balls, sure, but balls are still being created. Once the sim is returned to, all balls that were "created" are released at once. @veillette this causes lots of problems, including a large drop in performance.
Furthermore, this is not limited to browser tabs. All this happens the same when switching between sim screens.

**Comment by veillette** [comment]
Let's close this issue and open an issue where we keep track of the siisue regarding large DeltaTime interval
