### ISSUE TITLE
Massive "number" histogram while switching between displays

### ISSUE THREAD

**Issue by phet-steele** [phetsims/plinko-probability#15]
The "number" histogram display option auto-scales the y-axis to a max of 20 while it is used. However, switching to another option and back loses this auto-scaling, resulting in a massive graph filling the screen (when many balls have been dropped). @veillette this is a bug present in the Flash version (called the "legacy" version) that was tested on Win 10 browsers.

Before switching:
![smallnumber](https://cloud.githubusercontent.com/assets/5863899/15480518/3ccc14d8-20e3-11e6-960e-42d5c9e29b1e.PNG)

Switching options, then back to "number":
![bignumber](https://cloud.githubusercontent.com/assets/5863899/15480327/3a436c9e-20e2-11e6-8de0-7f193385b6d4.PNG)

**Comment by amanda-phet** [comment]
Just to be clear, the bug present here is not that the bars go off scale when "number" is selected (
I recall @dubson sharing that the bars going off the chart is a feature of this sim, not a bug.), but that when "number" is selected, it seems to be auto-scaling when it shouldn't.

**Comment by veillette** [comment]
Thanks @phet-steele for the info. We have reviewed the flash simulation pretty extensively
