### ISSUE TITLE
Translation of the statisticalPanel

### ISSUE THREAD

**Issue by veillette** [phetsims/plinko-probability#16]
![image](https://cloud.githubusercontent.com/assets/7633344/15709718/3765af84-27d4-11e6-87c8-e6f674c7a6f2.png)

One issue is to find out how much of the statistics panel should be translatable.
Right now, x bar, mu and sigma are hardwired. The "s" in s_mean is hardwired
but 'mean' is translatable. 's' and 'n' are currently translatable.  

```
  // strings
  var muGreekString = '\u03BC';
  var sigmaGreekString = '\u03C3';
  var xOverlineString = '\u0078\u0305';
  var meanString = require( 'string!PLINKO_PROBABILITY/mean' );
  var sMeanString = '\u0073<sub>' + meanString + '</sub>';
  var sString = require( 'string!PLINKO_PROBABILITY/s' );
  var nString = require( 'string!PLINKO_PROBABILITY/n' );
  var idealString = require( 'string!PLINKO_PROBABILITY/ideal' );
```

**Comment by ariel-phet** [comment]
@veillette all of those should be translatable. You will probably need to apply a rule whereby if the strings grow too large they scale down related to a max width of the panel. My guess is many translators will leave them as is, but we do want to allow the flexibility.

**Comment by Denz1994** [comment]
The text in the statistics box is now translatable. Logic was also added to all of the text to scale the font size if a translation becomes lengthy.

**Comment by Denz1994** [comment]
Test of elongated text, replicated by using "stringTest=double" in url.

![image](https://cloud.githubusercontent.com/assets/13894380/15778877/077f536c-2967-11e6-81d2-0e68159ae646.png)


This logic is followed  in the slider control panel as well for consistency.

![image](https://cloud.githubusercontent.com/assets/13894380/15779109/6d46d4ee-2968-11e6-9dcd-aa51dff6e3e7.png)

![image](https://cloud.githubusercontent.com/assets/13894380/15779077/4d8c949a-2968-11e6-8d4d-e793aedd2279.png)



Additionally, the y-axis label of the histogram follows similar logic.

![image](https://cloud.githubusercontent.com/assets/13894380/15779247/357a1282-2969-11e6-874c-73e7b400d67b.png)


![image](https://cloud.githubusercontent.com/assets/13894380/15779222/068db604-2969-11e6-9f31-6b991b0d9528.png)

**Comment by veillette** [comment]
This will be deployed in the next dev version (1.0.0dev4).Closing
