### ISSUE TITLE
Infinite number of balls on the intro screen

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/plinko-probability#17]
Steps to reproduce:
1. Go to intro screen
2. Select the xAll option
3. Press the play button and quickly press the reset all button
4. The balls will not stop, and will drop more than 100
5. Steps 2 and 3 can be repeated endlessly for a never ending number of balls

![image](https://cloud.githubusercontent.com/assets/19288972/15718568/487d3386-27e9-11e6-85b8-7eccee28c046.png)

This can also be done with the erase button, but only to 199 balls.
Steps to reproduce:
1. Select the xAll option
2. Press the play button
3. Quickly press the erase button
4. Press the play button a second time

![image](https://cloud.githubusercontent.com/assets/19288972/15717913/4907b41e-27e6-11e6-8286-429aa5f47087.png)

I saw this on Mac OSX 10.11.5. @phet-steele recreated this on Windows 10 chrome.
For phetsims/tasks/issues/608

Name: ‪Plinko Probability‬
URL: http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.3/plinko-probability_en.html
Version: 1.0.0-dev.3 2016-05-31 14:58:39 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36
Language: en-US
Window: 1404x707
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1f807347","branch":"master"},"babel":{"sha":"cdc2496f","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"a01a8e0f","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"joist":{"sha":"76d9aa21","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"plinko-probability":{"sha":"02182a89","branch":"master"},"scenery":{"sha":"30a08009","branch":"master"},"scenery-phet":{"sha":"124a6a03","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"sun":{"sha":"9ae0a8e1","branch":"master"},"tandem":{"sha":"0e40c775","branch":"master"}}

**Comment by memo330179** [comment]
This was addressed shortly after the dev deployment. Commit 91eaef3b4ae33211b0016fee15985da4466e61ef fixes the issue.

**Comment by memo330179** [comment]
Assigning @veillette  for review.

**Comment by veillette** [comment]
This commit should fix it. I'm assigning it back to @alynne-phet (to be checked once we redeploy a new dev)

**Comment by alynne-phet** [comment]
@veillette Verified.

**Comment by veillette** [comment]
Thanks. closing
