### ISSUE TITLE
Peg rotated too far at min/max binary probability

### ISSUE THREAD

**Issue by phet-steele** [phetsims/plinko-probability#18]
@amanda-phet @veillette I couldn't find anywhere in the design doc that explicitly states this, but in the Flash version of the sim, the flat part of a peg at min/max binary probability is only rotated ~45 degrees:
![screen shot 2016-06-02 at 10 08 48 am](https://cloud.githubusercontent.com/assets/5863899/15752163/073af46e-28aa-11e6-9015-0d0bea90b14c.png)
The new sim rotates twice that to ~90 degrees. It would make more sense to match the Flash version in this case, otherwise the ball is still hitting a rounded peg when falling from the top.
![screen shot 2016-06-02 at 10 02 33 am](https://cloud.githubusercontent.com/assets/5863899/15751926/289da8c8-28a9-11e6-8f10-4e79b4d49523.png)

For phetsims/tasks/issues/608

**Comment by veillette** [comment]
![image](https://cloud.githubusercontent.com/assets/7633344/15757844/9196853a-28d5-11e6-8295-9e39e5b9371b.png)



We can change it to something along the previous image if you prefer.

**Comment by veillette** [comment]
here is the commit https://github.com/phetsims/plinko-probability/commit/d9aca1ccf5f52a254b49110b918ec0743bd51a31

**Comment by phet-steele** [comment]
@veillette this looks good.
