### ISSUE TITLE
User can't easily add more balls after max count of 9999

### ISSUE THREAD

**Issue by phet-steele** [phetsims/plinko-probability#19]
@amanda-phet @veillette  In the Lab screen, after reaching the max bin count of 9999, a user should be able to add more balls after changing the number of rows or the value of binary probability. Changing either of those variables returns N to 0 in the same way the Erase button or Reset All button would, except hitting play will only prompt the "Out of Balls" dialogue. Seen on numerous platforms.

![pp01](https://cloud.githubusercontent.com/assets/5863899/15753095/8c6fa964-28ae-11e6-80fd-c5012ea60534.gif)

For phetsims/tasks/issues/608.

**Comment by memo330179** [comment]
That should fix it. Assigning to @veillette for review.

**Comment by veillette** [comment]
assigning to @alynne-phet for review

**Comment by alynne-phet** [comment]
@veillette The simulation does not stop at the max bin count of 9999. Has this been changed so there is no max bin count? I have been able to add over 9999 balls. Also, when using the query parameter 'lowerBallMaximum,' 100 balls fell before reaching the max bin count. Would you like me to create a new issue for this?

**Comment by veillette** [comment]
@alynne-phet 

One clarification: For the second tab, the number of balls can exceed 9999. However you should not be able to get the number of balls per bins to exceed 9999. When it is about to exceed this number, a dialog box should appear. 

It takes a lot of time to reach that number,but the query parameter lowerBallMaximum  makes it more amenable to testing.

On the first screen the max number refers to the total number of balls that lands.

**Comment by alynne-phet** [comment]
@veillette This makes much more sense. This issue has been fixed!

**Comment by veillette** [comment]
Thanks. Closing this issue.
