### ISSUE TITLE
Communicating max number of balls being reached, and how to handle further interactions

### ISSUE THREAD

**Issue by phet-steele** [phetsims/plinko-probability#20]
@amanda-phet on the Intro screen, when reaching the max N=100, shouldn't either the Play button be disabled, or pressing it again return N to 0 and drop more balls? I'd prefer the latter. To me this screen has a "trial" vibe to it, where a student will drop consecutive amounts of 100 balls to compare distributions. To currently do that, the student would either have to press the Eraser or Reset All buttons, then press Play again (a real pain). There have been multiple times after reaching N=100 that I've gone to press Play again expecting 100 more to come out (after returning N to 0 of course). This would be so nice :smile:, but if this isn't a good idea, then there should certainly be some sort of visual clue like the Play button being disabled. Not sure if I'd give my vote to showing the "Out of Balls" dialogue on this screen every single time a max is reached; that would get annoying quickly with how often and quickly a max is reached.

**Comment by veillette** [comment]
I can see @phet-steele point that it is very unlikely for someone to see the out-of-ball dialog in the "lab" screen but it is very likely to show up on the "intro" screen.

For your information, it would be easy to implement an approach that is different on the "Intro" screen and "Lab" screen. In addition, the Play and Pause button are custom buttons  (it is not the scenery-phet PlayPauseButton). In other words, because they are custom to plinko-probability, we have a lot of freedom about the look/behavior we want to use.

**Comment by amanda-phet** [comment]
In a 6/22 meeting we decided to make the play button disabled until the user clicks erase or reset all. 

I will interview on this sim 6/29 and 7/7 so we will get a chance to see how students interpret this!

**Comment by memo330179** [comment]
There are two possibilities of when the play button should be disabled. One is when the ball counter has reached 100 balls, and the other is when the user has queued 100 balls to drop.
![playbutton2](https://cloud.githubusercontent.com/assets/11654721/16303631/a81e644e-391f-11e6-90b9-784424a71cca.gif)
![playbutton](https://cloud.githubusercontent.com/assets/11654721/16303635/ab75fd32-391f-11e6-8b76-54501ea43490.gif)

**Comment by memo330179** [comment]
![playbutton2](https://cloud.githubusercontent.com/assets/11654721/16303631/a81e644e-391f-11e6-90b9-784424a71cca.gif)
![playbutton](https://cloud.githubusercontent.com/assets/11654721/16303635/ab75fd32-391f-11e6-8b76-54501ea43490.gif)

**Comment by amanda-phet** [comment]
@memo330179 That sounds good to me.

**Comment by veillette** [comment]
We will leave it open as we may get feedback from the student's interview.

**Comment by amanda-phet** [comment]
In last week's interview of this sim the student clicked reset all to interact again, so this behavior seems to be working.

**Comment by amanda-phet** [comment]
Since this worked well in an interview I'll go ahead and close the issue.
