### ISSUE TITLE
The Navigation icons are white rectangles

### ISSUE THREAD

**Issue by veillette** [phetsims/plinko-probability#23]
For the deployment of plinko-probability, we will need some artwork, namely two icons, one for the intro tab and the other for the lab tab. Currently they are white rectangles.

**Comment by amanda-phet** [comment]
Emailed icons to @veillette 6/29/16.

**Comment by Denz1994** [comment]
Added the icons provided by @amanda-phet to the homescreen and nav-bar. Thank you @amanda-phet for sending these. They look great!

**Comment by veillette** [comment]
@amanda-phet is unlikely to have an easy way to check this from master. We will reissue a dev candidate soon in any case. So closing.

**Comment by amanda-phet** [comment]
I figured out how to VPN :) They look really good to me!
