### ISSUE TITLE
"Out of Balls" before max count

### ISSUE THREAD

**Issue by phet-steele** [phetsims/plinko-probability#27]
On the Lab screen, when "Ball" view is being run and is then switched to "Path" or "None", the effective max count for a bin is lowered by an amount equal to the number of balls "left behind" on the board when switching views. In this video, there were 47 balls on the board before "None" was selected (hence 9999-47 = 9952).

![pp02](https://cloud.githubusercontent.com/assets/5863899/16495516/135b9444-3eab-11e6-9bb6-35e235be9fe6.gif)

Seen on OSX 10.11.5 Chrome. For phetsims/tasks/issues/630
Troubleshooting information:
Name: ‪Plinko Probability‬
URL: http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.5/plinko-probability_en.html
Version: 1.0.0-dev.5 2016-06-27 15:36:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Language: en-US
Window: 1920x1002
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"0ce3b9c8","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"e044eccd","branch":"master"},"dot":{"sha":"c9c05a5a","branch":"master"},"joist":{"sha":"fa5db70c","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"plinko-probability":{"sha":"af3b08d0","branch":"master"},"scenery":{"sha":"4476eb95","branch":"master"},"scenery-phet":{"sha":"52b783d9","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"sun":{"sha":"0d7e743b","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by veillette** [comment]
@memo330179, try to address this issue although if the fix is too complicated you can punt it as it is somewhat of an edge case.

**Comment by memo330179** [comment]
Should be solved assigning to @veillette for review.

**Comment by phet-steele** [comment]
@veillette this should be fixed, you can close after your review.

**Comment by veillette** [comment]
This is done. Closing
