### ISSUE TITLE
Long string issues

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/plinko-probability#29]
For stringTest=long, there is some text that extends into other elements on screen.

For the radio button text in the lab screen, I can imagine that text could reach the control panel:
![string2](https://cloud.githubusercontent.com/assets/6396244/16505665/4593df9a-3edb-11e6-9a9f-d7a5975ae126.PNG)

For the intro screen, it does seem unlikely that the strings would get long enough to hit the board, but please limit the length just in case.
![string1](https://cloud.githubusercontent.com/assets/6396244/16505704/7bab8c90-3edb-11e6-966d-323efe18a730.PNG)

**Comment by Denz1994** [comment]
I limited the maxWidth of the text nodes in the panels and now they scale the text size, with respect to an elongated text. The vertical radio button text no longer overlaps with the play button panel as well. Assigning to @jessegreenberg for review.

**Comment by jessegreenberg** [comment]
Great, thanks @Denz1994.  Closing.
