### ISSUE TITLE
use PhetColorScheme.RED_COLORBLIND ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#3]
This sim uses 'red' in several places. Evaluate whether any of them should be PhetColorScheme.RED_COLORBLIND.

**Comment by amanda-phet** [comment]
Yes I think this is a good place to use color-blind red, for sure. I will replace the current red in mockups to be sure it looks good overall, as well as view the mockups with color-blind filters.

**Comment by bereaphysics** [comment]
Viewing the sim with the color blind filter there is no possible sources of confusion. Since there is no conflict with other colors we will stick with the original red.
