### ISSUE TITLE
missing assets directory

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/plinko-probability#30]
The assets directory is missing for this sim. assets should contain the original files used to create images, audio, etc. For example, the file used to create images/container.png should be in assets/.

**Comment by veillette** [comment]
The directory was created 

We have seven png images checked in.
 
- [ ] container
- [ ] counter
- [ ] fraction
- [ ] intro-homescreen-icon
- [ ] intro-navbar-icon
- [ ] lab-homescreen-icon
- [ ] lab-navbar-icon

We would need the .ai files to be checked in the asset directory

We also have four sounds
- [ ] bonk-1-for-plinko
- [ ] bonk-2-for-plinko
 
We would like to get the .wav files checked in the asset directory

The images were created by @amanda-phet whereas the sounds were created to @jbphet . 

Assigning first to @amanda-phet to check in the .ai files into the asset directory.

**Comment by veillette** [comment]
@amanda-phet: I believe that it is now possible to upload binary files directly into GitHub from the web interface. If you run into any difficulties, you can email me the files instead.

**Comment by amanda-phet** [comment]
@jbphet do you have the sound files to upload?

**Comment by jbphet** [comment]
I used a program called "Propellerhead Reason" to generate the sounds.  I could upload the file, but it doesn't seem very worthwhile, since it isn't a program that anyone else is likely to have and thus couldn't edit it.  We should discuss in developer meeting whether such files should be stored in assets.

**Comment by samreid** [comment]
Everyone agrees we should check in the original asset files, including full resolution wave files, propellerhead files, etc.  If you wrote code to generate the audio, the code should be checked in, etc.

**Comment by andrewadare** [comment]
@jbphet Now that it's been decided to put the audio project files in the repo, can you add the Reason file(s) to assets/ when you get a chance? Thanks!

**Comment by pixelzoom** [comment]
@jbphet This sim is now in the "home stretch", so please add the assets for the audio files asap. Thanks.

**Comment by pixelzoom** [comment]
Moved check in of missing audio assets to https://github.com/phetsims/plinko-probability/issues/53.  All other assets appear to be present. Closing.
