### ISSUE TITLE
Complete sim credits

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/plinko-probability#32]
This issue is just to serve as a reminder to complete sim credits before publication.

**Comment by amanda-phet** [comment]
```
I will return to these to edit but this is the starting point.

credits: {
  leadDesign: 'Michael Dubson, Amanda McGarry',
  softwareDevelopment: 'Martin Veillette',
  team: 'Karina K. Hensberry, Trish Loeblein, Ariel Paul, Kathy Perkins',
  qualityAssurance: '',
  graphicArts: '',
  thanks: ''
}
```

**Comment by veillette** [comment]
This is what I have so far
```
      leadDesign: 'Michael Dubson, Amanda McGarry',
      softwareDevelopment: 'Denzell Barnett, Guillermo Ramos-Macias, Martin Veillette',
      team: 'Karina K. Hensberry, Trish Loeblein, Ariel Paul, Kathy Perkins',
      qualityAssurance: 'Ben Roberts, Steele Dalton, Amanda Davis'
```

**Comment by pixelzoom** [comment]
This sim is now in the "home stretch" so we need to wrap up this issue.  @amanda-phet Assigning this to you, since you're the lead.  Please specify any changes that need to be made.

Here's what the credits currently look like in curve-fitting-mains.js:

```js
  var simOptions = {
    credits: {
      leadDesign: 'Michael Dubson, Amanda McGarry',
      softwareDevelopment: 'Denzell Barnett, Guillermo Ramos-Macias, Martin Veillette',
      team: 'Karina K. Hensberry, Trish Loeblein, Ariel Paul, Kathy Perkins',
      qualityAssurance: 'Ben Roberts, Steele Dalton, Amanda Davis'
    }
  };
```

And in the About dialog:

![screenshot_97](https://cloud.githubusercontent.com/assets/3046552/18018443/26639788-6b94-11e6-8a39-f1fe69208966.png)

**Comment by phet-steele** [comment]
@pixelzoom QA credits are correct, but not alphabetical by last name. That's the only thing that needs changing in QA.

**Comment by pixelzoom** [comment]
QA names have been alphebetized.

**Comment by pixelzoom** [comment]
I moved @veillette to the front of the "Software Development" list, since he clearly did the bulk of the work.  And I added myself. Here's the latest About dialog:

![screenshot_102](https://cloud.githubusercontent.com/assets/3046552/18023982/e4851c4a-6bbd-11e6-9c09-bcd533e4dd78.png)

**Comment by amanda-phet** [comment]
I don't think there are any changes to make here.
