### ISSUE TITLE
branch: bouncyEndAnimation

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/plinko-probability#33]
Now that the sim is getting ready for publication, can the bouncyEndAnimation branch be pruned?  If it needs to be kept, please create an issue tittled "branch: bouncyEndAnimation" and describe its purpose.

**Comment by memo330179** [comment]
Removed the bouncyEndAnimation branch. Only the master branch exists now.

**Comment by veillette** [comment]
FYI, @memo330179 deleted the branch through github, without making a commit.  So we don't have a commit to show for it. Assigning to @jessegreenberg for review

**Comment by jessegreenberg** [comment]
Great, thanks!  @memo330179 I love your avatar pic.

**Comment by chrisklus** [comment]
this branch should be re-deleted as part of https://github.com/phetsims/special-ops/issues/198

**Comment by chrisklus** [comment]
branch was already deleted, closing
