### ISSUE TITLE
Exceeding max bin count

### ISSUE THREAD

**Issue by phet-steele** [phetsims/plinko-probability#34]
@veillette not sure if this is a result from the fix for #27 or not, but it's possible for me to go one ball over the max bin count by doing this:

(These steps are reversible)
1. On the Lab screen, keep the ball dropping method to "single"
2. Click play enough times to get just one away from the max (24 or 9998)
3. If you were using the "Ball" option, switch to "None". If you were using the "None" option, switch to "Ball"
4. You can now click the play button twice and reach 26 or 10000

This was tested on master at 11:30 AM on 7/1 with OSX 10.11.5 Chrome. There was some way I managed to reach 27 (10001) by some combination of switching between radio buttons, but I can't remember how.
![pp03](https://cloud.githubusercontent.com/assets/5863899/16529875/7690c93a-3f82-11e6-98d5-b0f2d04a3c6c.gif)

**Comment by memo330179** [comment]
We are now only removing the balls that have not landed or exited the peg board. This takes care of #27 as well.

**Comment by memo330179** [comment]
assigning to @phet-steele for review. You can test this out on master.

**Comment by phet-steele** [comment]
@memo330179 looks good to me, thanks
