### ISSUE TITLE
Update ballStep documentation

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/plinko-probability#35]
JSDoc documentation for 'ballStep' is only partially correct, and is actually the documentation for updatePosition.  In addition to updating the position, the ballStep function also updates peg information and emits events.  Since this is such an important function for this sim, so would you mind describing what full purpose in the JSDoc?

**Comment by veillette** [comment]
@memo330179 did most of the work on the position and the ballStep. I'm assigning it to you.

**Comment by memo330179** [comment]
I've added the documentation with the responsibilities the step function has. I tried to be descriptive, but not clutter the JSDoc.

**Comment by jessegreenberg** [comment]
Thanks @memo330179!  Looks great.
