### ISSUE TITLE
Describe IntroBall and LabBall in documentation

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/plinko-probability#38]
It is necessary to look at the code to understand what features are added to IntroBall and LabBall beyond the common Ball.js model element.  Please add some documentation to the top of IntroBall and LabBall to describe what is unique to these new model types.

**Comment by veillette** [comment]
@memo330179 you were responsible for this division so I'm assigning this to you.

**Comment by memo330179** [comment]
I have added a description of the IntroBall and LabBall and what makes them unique at the top of the file.

**Comment by jessegreenberg** [comment]
Thanks, @memo330179, that helps clarify the ball types.  Closing.
