### ISSUE TITLE
Remove copy-paste documentation

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/plinko-probability#43]
In IntroPlayPanel and BallRadioButtonsControl, it looks like the documentation for options was copied and pasted from somewhere else, can these lines be removed?

**Comment by memo330179** [comment]
The comment on top of the options did not provide anything useful in my opinion, and the comment on top of the fontOptions only made visual clutter. the fontOptions variable name make it clear that it is options for the font. Everything else explains what is going on.

**Comment by jessegreenberg** [comment]
Thanks @memo330179.  I agree that the variable name makes it clear enough what the object is for.  Closing.
