### ISSUE TITLE
Options pattern in SliderWithReadout

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/plinko-probability#45]
In SliderWithReadout, slider options are created as ```options.slider = _.extend(...```
Is this intentional? This is creating a new object under options called slider.  Would it be better to create a new variable called sliderOptions?

**Comment by jessegreenberg** [comment]
This issue might be resolved via #42, so that issue should be addressed first.

**Comment by jessegreenberg** [comment]
Ahh, I see and options.slider is created in SliderControlPanel.  ```options``` is a nested object.  I find this a little confusing because to reference the required values in SliderWithReadout, you need to go through a list of keys like ```options.slider.tick.step```.  Instead of creating a complex options object, could the HSlider be created in SliderControlPanel, and passed as a parameter to SliderWithReadout?  This might reduce complexity in both files.

**Comment by pixelzoom** [comment]
SliderControlPanel  was replaced with NumberControl in https://github.com/phetsims/plinko-probability/issues/42, so this is no longer an issue. Closing.
