### ISSUE TITLE
Move "N=100" panel up slightly on Intro screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/plinko-probability#47]
The top of the panel should be aligned on both the Intro and Lab screens so that the "N = " readout is aligned. 

![screen shot 2016-07-06 at 11 55 27 am](https://cloud.githubusercontent.com/assets/7852916/16628834/9812d5f2-4370-11e6-87ad-dc9910f82ef1.png)

**Comment by Denz1994** [comment]
Some alignment parameters were adjusted so the number display panels are aligned.

**Comment by amanda-phet** [comment]
While the panels seems to be aligned, the readout is still jumping a bit when switching between screens. Are the font sizes different?

**Comment by veillette** [comment]
The reason for the discrepancy is that one screen uses a panel whereas the other one uses an accordion box. The default values for spacing are probably different.  We should be able to match them very closely.
Will investigate

**Comment by veillette** [comment]
The text doesn't seem to toggle anymore on my screen,  but I don't have a very high quality monitor so I cant vouch for sure. 

 I'm assigning back to @amanda-phet to ascertain.

**Comment by amanda-phet** [comment]
Looks good to me. Thank you for making the custom fix!
