### ISSUE TITLE
incorrect sim title key

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#5]
In package.json:

> "simTitleStringKey": "PLINKO_PROBABILITY/plinko-probability.name"

In plinko-probability-strings_en.json:

> "simTitle": "Plinko Probability",

This will cause build tasks to fail, including README generation.

**Comment by pixelzoom** [comment]
You can change it in either package.json or plinko-probability-strings_en.json, but the keys need to match. Recommended to use plinko-probability.name, since that's most typical.

**Comment by bereaphysics** [comment]
The key was changed to plinko-probability.name in the string json file
