### ISSUE TITLE
Change Request: make statistics panel open by default

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/plinko-probability#51]
In an interview with a 6th grader, he opened the panel and found the "ideal" checkbox and was very interested in comparing the data with the ideal distribution. However, a math educator never found the checkbox! So, since the 6th grader was not intimidated by the statistics, I think we should have this panel open on startup (but allow the user to minimize if they want).

**Comment by veillette** [comment]
The statistics accordion box is set to open by default. (and set to open when one presses on reset)

**Comment by veillette** [comment]
work done, closing

**Comment by amanda-phet** [comment]
Thank you!
