### ISSUE TITLE
check in assets for audio files

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#53]
This issue was factored out of https://github.com/phetsims/plinko-probability/issues/30.

@jbphet said:
> I used a program called "Propellerhead Reason" to generate the sounds. I could upload the file, but it doesn't seem very worthwhile, since it isn't a program that anyone else is likely to have and thus couldn't edit it. We should discuss in developer meeting whether such files should be stored in assets.

@samreid said:
> Meeting July 21, 2016: Everyone agrees we should check in the original asset files, including full resolution wave files, propellerhead files, etc. If you wrote code to generate the audio, the code should be checked in, etc.

@andrewadare said:
> @jbphet Now that it's been decided to put the audio project files in the repo, can you add the Reason file(s) to assets/ when you get a chance? Thanks!

@pixelzoom said:
> @jbphet This sim is now in the "home stretch", so please add the assets for the audio files asap. Thanks.

**Comment by jbphet** [comment]
The original audio asset file has been added, closing.
