### ISSUE TITLE
bin numbers start from zero?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#54]
A design question for @amanda-phet ...

I noticed that the bins in this sim (and the original Flash version) are numbered starting from zero. I wanted to verify that this is really what's desired, and not a "programmer-ism" that snuck into the user presentation. 

I did a Google search, and sometimes I see the bins numbered from zero (http://ptrow.com/articles/Galton_June_07.htm), other times numbered from 1 (e.g. https://scratch.mit.edu/projects/92200985/).

**Comment by pixelzoom** [comment]
@ariel-phet also feel free to chime in if you have any information on this.

**Comment by ariel-phet** [comment]
@pixelzoom this was definitely intentional, but thanks for checking. Since the bins represent a histogram of the number of balls that have actually landed in the bin, they should definitely start from zero. 

Closing.
