### ISSUE TITLE
Use reproducible random number generators

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#55]
Related to https://github.com/phetsims/phet-io/issues/551...  I see that this sim uses `new Random` and `Math.random` in a few places.  So playback/record will not be reproducible.  Recommended to address this before publishing, since it's relatively simple.  @ariel-phet your call. @samreid feel free to chime in.

**Comment by pixelzoom** [comment]
TODO:

• Change 1 instance of `Math.random` to `phet.joist.random.nextDouble`
• Change 2 instances of `Random.random` to `phet.joist.random.random`

**Comment by samreid** [comment]
Yes, this is now part of the code review and would be nice to test if Plinko is going to get another full QA cycle.

**Comment by ariel-phet** [comment]
Yes, please address, thanks for pointing it out

**Comment by pixelzoom** [comment]
I replaced `Math.random` and `new Random`.  I also used `phet.joist.random.nextBoolean` in a couple of places where expression `( random.random() > 0.5 )` was used.

@samreid Would you mind taking a peek, to see if this looks ready for record/playback?

**Comment by samreid** [comment]
Looks good, I tested in the playback harness and everything was playing back perfectly.  In my preceding commits, I deprecated `Random.random` and switched plinko to use `Random.nextDouble` instead.  If all is well, you may close this issue, @pixelzoom

**Comment by pixelzoom** [comment]
If `Random.random` is deprecated, then perhaps it shouldn't be used to implement 3 of Random's other functions.   I.e., swap implementations of `random` and `nextDouble`, then use `nextDouble` internally.  @samreid what do you think?

**Comment by samreid** [comment]
Good plan, swapped above.

**Comment by pixelzoom** [comment]
... and switched to using `nextDouble` internally in this commit: https://github.com/phetsims/dot/commit/296008e9a0c69a790321db8f96bc7ec78e0e0962

Looks good. Closing.
