### ISSUE TITLE
usability tweaks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#56]
Discussed with @ariel-phet, a couple of usability tweaks requested for pointer areas and such:

- [x] Increase the font size for the Ball/Path/None radio button labels on the Lab screen, same size as "Rows" and "Binary Probability" in control panel.

- [x] Extend touchArea a bit to the right for radio buttons mentioned in (1).

- [x] Dilate touchArea for accordion box expand/collapse button in the lower-right panel of Lab screen.

**Comment by pixelzoom** [comment]
Changed completed. @ariel-phet please verify in this dev version:

http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.7/plinko-probability_en.html

**Comment by ariel-phet** [comment]
Checked on iPad 2, all looking very good and easy to click (even with my sausage fingers). Closing
