### ISSUE TITLE
rename PlinkoConstants?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#59]
The usual convention would be to name this either PlinkoProbabilityConstants or PPConstants.  Other types use the "PlinkoProbability" prefix (e.g. PlinkoProbabilityQueryParameters, PlinkoProbabilityCommonView, PlinkoProbabilityCommonModel).

I don't feel too strongly about which way to go.  But PlinkoProbabilityConstants is going to result in some very long lines at the sites where the constants are used.

**Comment by veillette** [comment]
I don't have a strong opinion about it.

**Comment by pixelzoom** [comment]
I renamed PlinkoConstants to PlinkoProbabilityConstants.  But I'm not going to inspect all 156 usages to check for lines that have gotten too long.  We'll address those as we encounter them during ongoing development and maintenance.
