### ISSUE TITLE
incorrect names for string files

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#6]
Related to #4. The string files are currently named "plinko-strings_<locale>.json".  Since the repo is named "plinko-probability", the string files must be named "plinko-probabiltiy-strings_<locale>.json". This violation of convention causes things in the build process (and eventually Rosetta) to fail.

**Comment by bereaphysics** [comment]
The string file for the english version was renamed. I deleted the other versions since there has been significant changes to the simulation.

**Comment by bereaphysics** [comment]
Closing
