### ISSUE TITLE
use ShadedSphereNode for balls

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#64]
BallNode (used to render the balls) is basically an implementation of a shaded sphere, with a specular highlight.  PhET already has something like this in common code, `scenery-phet.ShadedSphereNode`, and it should be used here.

**Comment by pixelzoom** [comment]
Done.  

This does change the look a bit, so I'd like @amanda-phet and @ariel-phet to verify. Before and after screenshots shown below.  The "After" look is now consistent with the look in other PhET sims. 

Before:

![screenshot_106](https://cloud.githubusercontent.com/assets/3046552/18094255/0cdb7426-6e90-11e6-8e3a-13960de02f9f.png)

After:

![screenshot_107](https://cloud.githubusercontent.com/assets/3046552/18094260/12085464-6e90-11e6-89c5-f8c081d01d95.png)

**Comment by pixelzoom** [comment]
Btw... I can also reproduce the original look, if you'd prefer.

**Comment by ariel-phet** [comment]
Mind publishing a new dev version so I can view on iPad?

**Comment by pixelzoom** [comment]
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.9/plinko-probability_en.html

**Comment by amanda-phet** [comment]
I think it looks fine but I'll want to update the artwork for the screen icons to match the new ball appearance.

**Comment by pixelzoom** [comment]
Or I can adjust the implementation to match the artwork?  Note that the artwork and implementation didn't match exactly previously -- specular highlight was a little off.

**Comment by ariel-phet** [comment]
Looks fine to me, but defer to @amanda-phet for particular look

**Comment by amanda-phet** [comment]
Let's use ShadedSphereNode, but I'll send you new artwork for the screen icons and scene selection icon that match slightly better. 

For example: 
![screen shot 2016-08-31 at 12 13 28 pm](https://cloud.githubusercontent.com/assets/7852916/18140827/71f41f22-6f74-11e6-90d3-58bf8e27cae9.png)

**Comment by pixelzoom** [comment]
@amanda-phet Sounds good. The asset files that you'll need to update are:

https://github.com/phetsims/plinko-probability/blob/master/assets/plinko-screen-icons.ai
https://github.com/phetsims/plinko-probability/blob/master/assets/cylinder.ai

I can create the .png files from the .ai files.

**Comment by amanda-phet** [comment]
I updated the .ai assets so they should be good to go.

**Comment by pixelzoom** [comment]
@amanda Please review this dev version. If it looks OK, you can close this issue.
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.10/plinko-probability_en.html

**Comment by pixelzoom** [comment]
@amanda-phet Please review this dev version. If it looks OK, you can close this issue.
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.10/plinko-probability_en.html

**Comment by amanda-phet** [comment]
Looks great. Thanks!
