### ISSUE TITLE
cylinders overflow on Intro screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#68]
I've seen this with the "x All" setting.  One of the cylinders may fill all the way to the top, and then some.  See screenshot below, where the center cylinder has 5 balls above its top edge.  

@amanda-phet is this OK or a bug?

![screenshot_108](https://cloud.githubusercontent.com/assets/3046552/18106687/17256d38-6ec2-11e6-973a-dfda9537bfde.png)

**Comment by ariel-phet** [comment]
This issue was definitely discussed with @veillette and his team. Because of the randomness this sometimes occurs, but I believe we all found this solution to be OK.

Still good to double-check with @amanda-phet.

**Comment by ariel-phet** [comment]
Looked over meeting notes. This overflow was approved on the 12/11/2015 meeting and is noted in the design doc meeting notes. Closing.
