### ISSUE TITLE
use PlayPauseButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#73]
This sim has is own `PlayButton` and `PauseButton`.  Why isn't is using the common-code button `scenery-phet.PlayPauseButton`?

**Comment by pixelzoom** [comment]
The current buttons in this sim look like this (currently flat, but could be 3D):

![screenshot_04](https://cloud.githubusercontent.com/assets/3046552/18111077/fa3b5a30-6ed9-11e6-9e5a-0323200cc315.png)
![screenshot_05](https://cloud.githubusercontent.com/assets/3046552/18111080/fce812be-6ed9-11e6-96f6-4cd8aa8763ac.png)

`scenery-phet.PlayPauseButton` has a different look:

![screenshot_06](https://cloud.githubusercontent.com/assets/3046552/18111118/469c8a48-6eda-11e6-983a-e8497bf698b0.png)
![screenshot_07](https://cloud.githubusercontent.com/assets/3046552/18111122/4bbf355c-6eda-11e6-9317-0625edbc1ee2.png)

And I'm not sure if the play and pause states can have different colors.

@ariel-phet Do you want me to investigate this, or leave as is?

**Comment by pixelzoom** [comment]
PlayButton is 56 lines of code.
PauseButton is 58 lines of code.

Not a huge savings here by switching to PlayPauseButton, just the consistency of using common code.

**Comment by pixelzoom** [comment]
RoundButtonView has a setter for baseColor, so likely that the play and pause states could have different colors.

**Comment by amanda-phet** [comment]
I would prefer the common code button but with different colors. The green button was effective in interviews and I don't think the light blue would be bold enough.

**Comment by ariel-phet** [comment]
@pixelzoom agree with @amanda-phet

**Comment by pixelzoom** [comment]
OK, I will investigate using PlayPauseButton.

**Comment by pixelzoom** [comment]
Investigated and decided that this is not worth the trouble.  On the "Intro" screen, there is no pause button, so it's not easy to use `PlayPauseButton`, we'd still need `PlayButton`.   So I'll give `PlayButton` and `PauseButton` a quick cleanup, then close this issue.

**Comment by pixelzoom** [comment]
Cleanup completed, closing.

**Comment by pixelzoom** [comment]
Also identified a more efficient way of implementing the pause icon in `PlayPauseButton`, tracking in https://github.com/phetsims/scenery-phet/issues/268.
