### ISSUE TITLE
statistics panel pixel polishing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#74]
After discussing with @ariel-phet... This panel in the Lab screen could use a little pixel polishing:

![screenshot_08](https://cloud.githubusercontent.com/assets/3046552/18111914/9929bfc8-6ee0-11e6-9431-76bfba51d76d.png)

I reclaimed a little vertical space in @7628bd134f4821f43137acfbadda78dfa1006f47 and @e9a51566a37480c4b3c7df9d189822f942bed761, so we have some space to play with.

**Comment by amanda-phet** [comment]
What is the pixel-polishing that is being proposed?

**Comment by ariel-phet** [comment]
@amanda-phet - @pixelzoom and I discussed a few possibilities

1. He felt the box was a bit tight, so expanding the panel a bit vertically
2. Aligning the first 2 blue rows (mu and sigma) with the first two red rows (seems odd not to have these aligned right now)
3. Possibly moving the checkbox down a little so things are also not so tightly spaced

Any polishing here would be pending your approval - but @pixelzoom was keen on trying to clean things up a bit so I told him to take a stab at it.

**Comment by pixelzoom** [comment]
@amanda-phet Does what @ariel-phet described above sound reasonable?

**Comment by amanda-phet** [comment]
Sounds good to me! I didn't notice that the rows weren't aligned but they definitely should be. 

After you make changes, can you just confirm that the "N = " readout is aligned on both screens?

**Comment by pixelzoom** [comment]
The "N =" readout is definitely not aligned on both screens. And it's currently impossible to do that (accurately) in a language-independent way.

**Comment by amanda-phet** [comment]
I see. I think we just had the top of those two panels aligned so it didn't jump too much between screens. However, between dev.6 and dev.7 when the slider changes were happening, the rows/probability panel grew quite a bit and pushed the stats panel way down. 

After you finish this issue can we try to adjust things a bit more?

**Comment by pixelzoom** [comment]
> After you finish this issue can we try to adjust things a bit more?

Yes. I will need to determine a hardcoded (yuck) vertical offset for the "N=" panel on the Intro screen, such that it matches the position of the "N=" panel on the Lab screen.  It will be guaranteed to look correct only for English.  And if someone changes the Lab screen in the future, the alignment is likely to be lost.

**Comment by pixelzoom** [comment]
Here's the revised panel, reviewed with @amanda-phet and she said it looks good:

![screenshot_11](https://cloud.githubusercontent.com/assets/3046552/18184508/a6050ad2-7056-11e6-8247-b577a06361e1.png)

**Comment by pixelzoom** [comment]
Here's the revised panel, reviewed with @amanda-phet and she said it looks good:

![screenshot_12](https://cloud.githubusercontent.com/assets/3046552/18184642/36cd822e-7057-11e6-88bf-f26899ea57d4.png)

**Comment by pixelzoom** [comment]
Reviewed the changes with @ariel-phet also, looks good. Pixel polishing done.  

I will now vertically align the 2 "N=" panels.

**Comment by pixelzoom** [comment]
Moved the "N=" alignment issue to https://github.com/phetsims/plinko-probability/issues/77.

Closing.
