### ISSUE TITLE
make "N=" panels line up when switching screens

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#77]
Requested by @amanda-phet in https://github.com/phetsims/plinko-probability/issues/74#issuecomment-243845881:

> can you just confirm that the "N = " readout is aligned on both screens?

I replied:
> The "N =" readout is definitely not aligned on both screens. And it's currently impossible to do that (accurately) in a language-independent way.

@amanda-phet asked:
> I see. I think we just had the top of those two panels aligned so it didn't jump too much between screens. However, between dev.6 and dev.7 when the slider changes were happening, the rows/probability panel grew quite a bit and pushed the stats panel way down.
> 
> After you finish this issue can we try to adjust things a bit more?

I replied:
> Yes. I will need to determine a hardcoded (yuck) vertical offset for the "N=" panel on the Intro screen, such that it matches the position of the "N=" panel on the Lab screen. It will be guaranteed to look correct only for English. And if someone changes the Lab screen in the future, the alignment is likely to be lost.

**Comment by pixelzoom** [comment]
The Play control panel also jumps around.

**Comment by pixelzoom** [comment]
@amanda-phet It's not perfect, but I improved the alignment of both the Play and "N=" panels when switching between screens. You can compare in these 2 dev versions:

Before changes:
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.10/plinko-probability_en.html

After changes:
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.11/plinko-probability_en.html

Is this good enough? If so, please close this issue.

**Comment by pixelzoom** [comment]
@amanda-phet ping.

**Comment by amanda-phet** [comment]
Looks good thank you!
