### ISSUE TITLE
Statistics panel should be closed by default

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#81]
Statistics panel should be closed by default.

Skype discussion:
> [9/9/16, 5:24:40 PM] Ariel Paul: quickly...on the Lab screen is the stats panel supposed to be open by default?
[9/9/16, 5:24:56 PM] Chris Malley: AFAIK, yes. I didn't change it.
[9/9/16, 5:25:10 PM] Ariel Paul: OK, good to know
[9/9/16, 5:27:09 PM] Chris Malley: Hmmm...  It was closed by default up until 1.0.0-dev.5.  In 1.0.0-dev.6, it was open by default, and has been ever since.  All of that was before I started working on it.  So I couldn't tell you what the correct default state is.

Design document for this panel says:
> an expandable window to show the statistical values (text size 18) based on the trials (RGB red) and the theoretical statistical values (RGB blue). 
*default: collapsed, with just “N = ” visible*
> 
> The checkbox will show an outline of the underlying (ideal) distribution bars on the graph. 
*default: unchecked*

**Comment by pixelzoom** [comment]
Done. Closing.

**Comment by amanda-phet** [comment]
This change was done based on interviews. I apologize if there was not sufficient documentation. Can we change it back?

**Comment by ariel-phet** [comment]
@amanda-phet yes, no problem, it was a one line change (sorry something I noticed and seemed to recall the original design had it closed, but good to know it work well opened in interviews!)

**Comment by pixelzoom** [comment]
Yes we can change it back. @amanda-phet Please note this somewhere in the design document.

**Comment by amanda-phet** [comment]
@pixelzoom I changed the design spec and added meeting notes.

**Comment by pixelzoom** [comment]
Reverted to open by default. Closing.
