### ISSUE TITLE
create sim screenshot

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#82]
We need a screenshot for this sim's webpage etc.

@amanda-phet Please send me a screenshot showing how you'd like the final screenshot to look. Then assign back to me and I'll create the final screenshot.

**Comment by amanda-phet** [comment]
<img width="941" alt="screen shot 2016-09-15 at 10 28 15 am" src="https://cloud.githubusercontent.com/assets/7852916/18558141/360f32d2-7b2f-11e6-8b73-5ea869904fb3.png">


Something like this where the balls are in motion but the red bars don't line up exactly with the ideal bars. 6 rows and p=0.31.

**Comment by pixelzoom** [comment]
[Master checklist](https://github.com/phetsims/plinko-probability/issues/12) indicates these requirements for screenshot:

> 2048x1344, PNG, 32-bit color, browser chrome stripped

**Comment by pixelzoom** [comment]
To "PhET Developers" on Skype:
> Anyone want to volunteer to create the screenshot for Plinko?  I don't have the necessary equipment. Self assign if you're willing: https://github.com/phetsims/plinko-probability/issues/82

**Comment by pixelzoom** [comment]
Screenshot can be done out of either master or 1.0 branch, they will look the same.

**Comment by jessegreenberg** [comment]
@pixelzoom screenshot taken and committed to master, let me know if anything needs to be changed in about the image, I can take another.

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg, looks good to me.

@amanda-phet Does this look OK to you?
https://github.com/phetsims/plinko-probability/blob/master/assets/plinko-probability-screenshot.png

**Comment by amanda-phet** [comment]
Yes it does!
