### ISSUE TITLE
Lead designer "sign off"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/plinko-probability#83]
@amanda-phet Please complete these items in the [Plinko Probability master checklist](https://github.com/phetsims/plinko-probability/issues/12) before the simulation begins RC testing.

- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests

**Comment by pixelzoom** [comment]
Labeling with high priority, since the sim is now in dev testing and is likely to be in RC testing before the end of this week.

**Comment by amanda-phet** [comment]
Done.

**Comment by pixelzoom** [comment]
👍
