### ISSUE TITLE
[Edge] Red line extends along the bottom of the histogram

### ISSUE THREAD

**Issue by phet-steele** [phetsims/plinko-probability#87]
Both screens, any histogram mode other than the cylinders, and regardless of any sim state. This red line lays across the bottom of the bin (regardless of the contents of the bin). It IS covered by the ideal graph when it is enabled.

![edgered](https://cloud.githubusercontent.com/assets/5863899/18590555/8bf6fd52-7bec-11e6-856e-43996a5e2a1a.PNG)

Seen on Edge 38.14393.0.0, for phetsims/tasks/issues/696. 
Name: ‪Plinko Probability‬
URL: http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.16/plinko-probability_en.html
Version: 1.0.0-dev.16 2016-09-13 20:39:43 UTC
Features missing: touch
Flags: pointerEnabled, pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
Language: en-US
Window: 1536x747
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"e0192608","branch":"master"},"babel":{"sha":"ca508dea","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"9f0bb7ca","branch":"master"},"dot":{"sha":"39436598","branch":"master"},"joist":{"sha":"752d3a03","branch":"master"},"kite":{"sha":"73302899","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"plinko-probability":{"sha":"cbd8dd29","branch":"master"},"query-string-machine":{"sha":"20686a62","branch":"master"},"scenery":{"sha":"e78ee413","branch":"master"},"scenery-phet":{"sha":"f0fc9ae8","branch":"master"},"sherpa":{"sha":"bcc28cd6","branch":"master"},"sun":{"sha":"459de68b","branch":"master"},"tandem":{"sha":"4a8edbc9","branch":"master"},"vibe":{"sha":"b422db9c","branch":"master"}}

**Comment by pixelzoom** [comment]
@phet-steele said:
> This red line lays across the bottom of the bin (regardless of the contents of the bin).

Does there need to be at least 1 ball in a bin (as in the screenshot that you provided), or is this read line present when all bins (and the histogram) are empty?

**Comment by phet-steele** [comment]
@pixelzoom there does not need to be anything in the bin. I put one in just to demonstrate that it remains when the histogram is populated. There is no red line when the histogram is in ball mode. From start-up for example:

![edgeredstart](https://cloud.githubusercontent.com/assets/5863899/18596211/48b9864a-7c05-11e6-9835-d8d02f2e3626.PNG)

**Comment by pixelzoom** [comment]
Inspecting the code (HistogramNode), a bar (rectangle) is created for every bin, and the height of the bars is adjusted. If a bin is empty, this results in a scenery.Rectangle whose height is zero. Since each bar is stroked, I suspect that what we're seeing is Edge's attempt to render a zero-height rectangle. The fix for this is to make zero-height rectangles invisible.

**Comment by pixelzoom** [comment]
I attempted to fix this by making any zero-height bars invisible.  Since I don't have an Edge test machine, I'll need @phet-steele's assistance in verifying whether this fixed the issue.  @phet-steele please test drive this dev version:

http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.18/plinko-probability_en.html

**Comment by pixelzoom** [comment]
@phet-steele When you test this, also be on the lookout for any collateral damage to the histogram - e.g. non-zero bars that don't appear, bigfoot sightings, etc.

**Comment by phet-steele** [comment]
I don't about you @pixelzoom, but everything looks fine to me.

![edgenored](https://cloud.githubusercontent.com/assets/5863899/18597463/6663e306-7c0b-11e6-9954-9c947a83209e.PNG)

**Comment by pixelzoom** [comment]
Fantástico. Closing.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/tasks/issues/696.
