### ISSUE TITLE
QA Credits

### ISSUE THREAD

**Issue by phet-steele** [phetsims/plinko-probability#89]
Please add the following team members to the QA credits:

- Bryce Griebenow

@pixelzoom, please keep this open until the sim is published in case additional people need to be added, you never know!

**Comment by pixelzoom** [comment]
This was supposed to have been completed in https://github.com/phetsims/plinko-probability/issues/32.  But I understand that additional testers may be added during RC process. Just keep in mind that it now requires changing credits in 2 branches (master and 1.0).

**Comment by phet-steele** [comment]
> additional testers may be added during RC process

@pixelzoom this is precisely what happened with Bryce 😄

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/tasks/issues/702

**Comment by pixelzoom** [comment]
I'm going to wait until testing is completed to add anyone, since this is something that can be done once without requiring a test cycle.

**Comment by phet-steele** [comment]
@pixelzoom, after adding Bryce, the QA credits will be accurate.

**Comment by pixelzoom** [comment]
QA credits updates in master and 1.0 branches, will appear in 1.0.0-rc.2.  Closing.
