### ISSUE TITLE
Add attributions for the image artwork

### ISSUE THREAD

**Issue by samreid** [phetsims/plinko-probability#9]
We need to record where the images came from.

**Comment by samreid** [comment]
@amanda-phet I noticed you helped with some of the other images in this simulation.  Can you comment on where this

![image](https://cloud.githubusercontent.com/assets/679486/8810957/d13a1014-2faf-11e5-883a-b5a167328335.png)

and this

![image](https://cloud.githubusercontent.com/assets/679486/8810960/d5e8f6b6-2faf-11e5-95ad-1d296bdee304.png)

came from?  Did we draw them?

**Comment by amanda-phet** [comment]
I drew them.

**Comment by samreid** [comment]
Perfect, thanks!  I added the attributions in the above commit, closing.

**Comment by pixelzoom** [comment]
FYI... In @6dcc5ccecc1bde0515236b87a0c0e41fe3241c52, container.png and container.ai were renamed to cylinder.png and cylinder.ai respectively, because their corresponding Property value is 'cylinder'.
